const actionTypes = {
  ADD_BIRD: 'ADD_BIRD',
  ADD_BIRD_SUCCEEDED: 'ADD_BIRD_SUCCEEDED',
  ADD_BIRD_FAILED: 'ADD_BIRD_FAILED',
  GET_ALL_BIRDS_FETCH_REQUESTED: 'GET_ALL_BIRDS_FETCH_REQUESTED',
  GET_ALL_BIRDS_FETCH_SUCCEEDED: 'GET_ALL_BIRDS_FETCH_SUCCEEDED',
  GET_ALL_BIRDS_FETCH_FAILED: 'GET_ALL_BIRDS_FETCH_FAILED'
};

export default actionTypes;
